"""
Django settings for bibliolab.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

# Percorso base usato per risolvere risorse relative al progetto, come i file statici.
BASE_DIR = Path(__file__).resolve().parent.parent

# Impostazioni basate sulle variabili d'ambiente.
# Questi valori sono attesi dall'ambiente di esecuzione o dal container.
# SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
# Cerca nel file .env, se non la trova usa la stringa di backup (valida solo per lo sviluppo locale!)
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "chiave-temporanea-di-sviluppo-12345")

DEBUG = os.getenv("DJANGO_DEBUG") == "True"

# In fase di sviluppo l'API è raggiungibile da qualsiasi host.
# In produzione questo dovrebbe essere ristretto ai domini effettivi del deployment.
ALLOWED_HOSTS = ["*"]

# Applicazioni Django caricate dal progetto.
# Ogni app contribuisce con modelli, URL, viste e comportamento admin.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'drf_spectacular',
    'corsheaders',
    'catalogo.apps.CatalogoConfig',
]

# Pipeline dei middleware.
# Le richieste attraversano questi componenti in ordine fisso prima di arrivare alla view.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Punto di ingresso per il routing delle URL.
ROOT_URLCONF = 'bibliolab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bibliolab.wsgi.application'


# Configurazione del database.
# Il nome del servizio 'db' viene usato perché Docker Compose lo risolve come host del database.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",

        "NAME": os.getenv("POSTGRES_DB"),

        "USER": os.getenv("POSTGRES_USER"),

        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),

        "HOST": "db",

        "PORT": "5432",
    }
}


# Regole di validazione della password applicate durante la creazione e l'aggiornamento degli utenti.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Impostazioni di localizzazione.
LANGUAGE_CODE = 'it-it'
TIME_ZONE = 'Europe/Rome'
USE_I18N = True
USE_TZ = True

# Impostazioni dei file statici.
# WhiteNoise viene usato per servire gli asset statici in modo efficiente.
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Impostazioni predefinite di DRF.
# L'autenticazione JWT è attiva globalmente e tutti gli endpoint richiedono autenticazione
# a meno che una view specifica non permetta accesso anonimo.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Origini frontend consentite.
# Questi sono gli unici indirizzi autorizzati a chiamare l'API dal browser.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Ciclo di vita dei token JWT.
# I token di accesso hanno durata breve; quelli di refresh servono per ottenerne di nuovi.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=5),
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'