# Generated by Django 5.2.6 on 2026-06-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('librarian', 'Librarian'), ('admin', 'Admin')], default='reader', max_length=20),
        ),
    ]
