# Generated by Django 5.2.6 on 2026-07-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autore',
            options={'verbose_name_plural': 'Autori'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name_plural': 'Libri'},
        ),
    ]
